# Generated by Django 5.0.3 on 2024-03-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_setting_description_remove_setting_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='banner_image',
            field=models.ImageField(default='banners/default_banner.jpg', upload_to='banners/'),
        ),
    ]
