# Generated by Django 5.0.3 on 2024-03-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_clips_remove_screenshot_user_profile_delete_clip_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clips',
        ),
    ]
