# Generated by Django 5.0.3 on 2024-03-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_clips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_name',
            new_name='user',
        ),
    ]
