# Generated by Django 5.0.3 on 2024-03-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_user_name_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='user_name',
        ),
    ]
