# Generated by Django 5.0.3 on 2024-03-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_current_status_game_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_status',
            field=models.CharField(choices=[('Downloaded', 'Yuklu'), ('Not-Downloaded', 'Yuklu Degil')], default='Downloaded', max_length=50),
        ),
    ]
