# Generated by Django 5.0.3 on 2024-03-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_game_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_status',
            field=models.CharField(choices=[('Downloaded', 'Downloaded'), ('Not-Downloaded', 'Not-Downloaded')], default='Downloaded', max_length=50),
        ),
    ]
