# Generated by Django 5.0.3 on 2024-03-15 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_game_current_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, default='images/default.jpg', upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='featured_game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.featuredgame'),
            preserve_default=False,
        ),
    ]
