# Generated by Django 5.0.3 on 2024-03-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_game_current_status_game_date_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('trailer_image', models.ImageField(blank=True, default='images/default.jpg', upload_to='images/')),
                ('avatar', models.ImageField(blank=True, default='images', upload_to='images/')),
            ],
        ),
    ]
