# Generated by Django 5.0.3 on 2024-03-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_gametrailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametrailer',
            name='developer',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
