# Generated by Django 5.0.3 on 2024-03-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_gametrailer_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametrailer',
            name='avatar',
        ),
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
