# Generated by Django 5.0.3 on 2024-03-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_remove_gametrailer_avatar_game_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='downloads',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.CharField(max_length=20),
        ),
    ]
