# Generated by Django 5.0.3 on 2024-03-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_game_downloads_alter_game_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default='images', upload_to='images/')),
                ('image2', models.ImageField(blank=True, default='images', upload_to='images/')),
                ('image3', models.ImageField(blank=True, default='images', upload_to='images/')),
                ('image4', models.ImageField(blank=True, default='images', upload_to='images/')),
                ('developer', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=20)),
                ('trailer_url', models.URLField(blank=True)),
            ],
        ),
    ]
