# Generated by Django 5.0.3 on 2024-03-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_newsgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsgame',
            name='image5',
            field=models.ImageField(blank=True, default='images', upload_to='images/'),
        ),
    ]
