# Generated by Django 5.0.3 on 2024-03-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_newsgame_image5'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsgame',
            name='header',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
